# Common variables
x-common-variables: &common-variables
  MYSQL_HOST: ${MYSQL_HOST}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

# Specific variables for FastAPI
x-fastapi-variables: &fastapi-variables
  <<: *common-variables
  PORT: ${PORT}
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}

services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      <<: *common-variables
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h localhost
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      <<: *fastapi-variables
    volumes:
      - ./backend:/app
    depends_on:
      mysql-db:
        condition: service_healthy
    working_dir: /app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileReact
    ports:
      - "3000:3000"
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:8000
      - VITE_BASE_PATH=/
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
